---
sudo: required
services:
  - docker
language: php
php:
  - 7.1
env:
  - WP_ENV=testing
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.composer/vendor
    - vendor
before_install:
  - docker-compose -v
  - docker -v
  - composer self-update
  - composer install
install:
before_script:
script:
  - sudo -E docker-compose -f docker-compose.yml run ci
after_script:
  - docker ps -a
  - docker-compose logs

