version: '2'
services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile-herokuphp
    image: herokuphp
    command: bash tools/ci.sh
    working_dir: /app/user
    volumes:
      - .:/app/user
    links:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    volumes:
      - mysqldata:/var/lib/mysql
    # ports:
    #   - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  redis:
    image: redis:3.2
    # ports:
    #   - 6379:6379

volumes:
  mysqldata: {}
